### ISSUE TITLE
Error Generating Documents

### ISSUE THREAD

**Issue by AndresPMD** [biswassanket/synth_doc_generation#1]
Congrats on your project.

However, I have a doubt.
When I try to run your code, I have the following problem:

Error 754: Value unpacked sequence not defined. Document not generated.

**Comment by biswassanket** [comment]
I think there might be a problem with the environment you created. Please make sure you have installed the conda environment correctly.  Let me know if you have further issues.

**Comment by AndresPMD** [comment]
It's solved!
Thanks amazing solution asap!

Good luck with the ongoing fundamental research!
